### ISSUE TITLE
visitorMethod时调用链分析错误

### ISSUE THREAD

**Issue by userzgc** [F-JH/static-chain-analysis#2]
就是子类重写父类的方法，子类的方法引用调用最后会计算到父类下面
![image](https://user-images.githubusercontent.com/47551857/223404273-ac2aeb36-5ef8-4517-9a8e-2632e4054931.png)
<img width="816" alt="image" src="https://user-images.githubusercontent.com/47551857/223404359-e3cc6cb5-01ee-48ea-99b1-31d395514184.png">

想问下这里是何时将函数的调用链路list赋值的我看了很多资料都没有说到visitMethodInsn和visitMethod方法之间的关系
![image](https://user-images.githubusercontent.com/47551857/223404594-f91e814d-6cbf-436e-91bc-9bcfeb7831c3.png)

**Comment by ByteWong-YingQueSTing** [comment]
谢谢，已收到你的邮件。---------  黄志杰（Byte）.

**Comment by F-JH** [comment]
`就是子类重写父类的方法，子类的方法引用调用最后会计算到父类下面`
是的，这里面的过程是这样：
1.先检索出所有interface和abstract类；
2.你的DelEsListener类因为继承了ActionListener，所以会使用putInterfaceEntry记录这一条映射关系
3.当项目里再另一个地方调用:
    ActionListener<Type> actionListener = new DelEsListener();
    actionListener.onResponse(xx);
    此时在ASM里其实是 methodVisitor.visitMethodInsn["com/xx/xx/ActionListener"] 而不是 methodVisitor.visitMethodInsn["com/xx/xx/DelEsListener"]
4.因此静态分析只能做到：A -> ActionListener.onResponse -> DelEsListener.onResponse

设想如果有多个类继承了interface，那么会是这样：
A -> ActionListener.onResponse -> DelEsListener.onResponse
                                                        -> AddEsListener.onResponse
                                                        -> ModifyEsListener.onResponse
这个时候三个实体类方法有任何一个有改动都会导致判断这条链有变动
———————————————————————————————————————————————————————————————
以上是interface和abstract类的处理流程，我看了一下，如果换成普通类，确实不会记录这样的映射关系，应该就是你说的
`子类重写父类的方法，子类的方法引用调用最后会计算到父类下面`的情况

**Comment by chenju0606** [comment]
我最近也在尝试这样的调用链分析，对于上面的2个问题有一些想法
1、关于子类与父类的方法调用，是不是可以适用JavaParser来解析@override注解并分析具体是重写了方法或者继承了方法或者实现了方法，并依次建立父类与子类的方法关系
2、动态代理模式我觉得可以先分析所有的@interface，然后建立pointcut和advicemethod的调用关系，并最后建立方法与pointcut method的关系

不过对于Feign调用的问题和配置文件引用另外的微服务之间的调用关系我一直没有很好的解决方法，您这边是有实现的么

**Comment by ByteWong-YingQueSTing** [comment]
谢谢，已收到你的邮件。---------  黄志杰（Byte）.

**Comment by userzgc** [comment]
时隔两月 才看到大佬的回复，我也是看其他的方案发现 多态 AOP 反射这种用动态分析可以更好的解决问题，请收下我的膝盖
